# Generated by Django 4.2.10 on 2024-04-28 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0002_alter_phone_content_alter_phone_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.FloatField(verbose_name='Цена (с)'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='tel',
            field=models.IntegerField(blank=True, default=996, max_length=12, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='phone',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='phone.state', verbose_name='Состояние'),
            preserve_default=False,
        ),
    ]
