# Generated by Django 4.2.10 on 2024-07-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0007_alter_size_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='tel',
            field=models.IntegerField(blank=True, default=996700909915, max_length=12, null=True, verbose_name='Номер телефона'),
        ),
    ]
